### ISSUE TITLE
remove libsmr dependencies

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/verifica#1]
`libsmr` libs are obsolete and will not be included in github/travis/copr integration
(@dcesari, @pat1: chime in if I'm wrong)

There are some checks about its libraries in `configure.ac`:
```
AC_CHECK_LIB([mega], [jeladata5], , AC_MSG_ERROR([mega library not found]), )
AC_CHECK_LIB([hibu], [ngetpoint], , AC_MSG_ERROR([hibu library not found]), )
AC_CHECK_LIB([emos], [gribex], , AC_MSG_ERROR([emos library not found]), )
AC_CHECK_LIB([grib_util], [findgrib], , AC_MSG_ERROR([gributil library not found]), )
```
but in the code `libmega` and `libhibu` seem unused, while `findgrib` seems to be used (and should be removed/replaced)

**Comment by dcesari** [comment]
All correct, `findgrib` may require some nontrivial refactoring (and maybe a new issue?).

**Comment by brancomat** [comment]
This seems to be closed by version 5
